enum UIStatusEnum {
    SELECT_CARDS = "SELECT_CARDS",
    DISCARD_CARDS_FROM_HAND = "DISCARD_CARDS_FROM_HAND",
    DISCARD_CARDS_FROM_HAND = "DISCARD_CARDS_FROM_HAND",
    DISCARD_CARDS_FROM_HAND = "DISCARD_CARDS_FROM_HAND",
    DISCARD_CARDS_FROM_HAND = "DISCARD_CARDS_FROM_HAND",
    DISCARD_CARDS_FROM_HAND = "DISCARD_CARDS_FROM_HAND",
}

export default PhasesEnum
