enum UIStatusEnum {
    SELECT_CARDS = "SELECT_CARDS",
    DISCARD_CARDS_FROM_HAND = "DISCARD_CARDS_FROM_HAND",
    SELECT_COLUMN_TO_PLAY_STATE = "SELECT_COLUMN_TO_PLAY_STATE",
    SELECT_CARDS_STATE = "SELECT_CARDS_STATE",
}

export default UIStatusEnum
